baseURL = "https://ricardosilva.xyz"
copyright = "Ricardo da Silva"
title = "Blog do Ricardinho"
pagination.pagerSize = 3 # for demonstration of pagination
languageCode = "pt-br"
defaultContentLanguage = "pt-br"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
theme = "tailwind"
enableGitInfo = true
sectionPagesMenu = "main"

[markup]
  _merge = "deep"
  [markup.goldmark]
    duplicateResourceFiles = false
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    linkifyProtocol = 'https'
    strikethrough = true
    table = true
    taskList = true
  [markup.goldmark.extensions.cjk]
    eastAsianLineBreaks = false
    eastAsianLineBreaksStyle = 'simple'
    enable = false
    escapedSpace = false
  [markup.goldmark.extensions.extras]
    [markup.goldmark.extensions.extras.delete]
      enable = true
    [markup.goldmark.extensions.extras.insert]
      enable = true
    [markup.goldmark.extensions.extras.mark]
      enable = true
    [markup.goldmark.extensions.extras.subscript]
      enable = true
    [markup.goldmark.extensions.extras.superscript]
      enable = true

[taxonomies]
category = "categorias"
tag = "tags"
series = "series"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.x]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true
