[en]
  languageCode = 'en'
  languageName = 'English'
  title = "Ricardinho's Blog"
  weight = 1
  [en.menu]
  [[en.menu.main]]
  identifier = "about"
  name = "About"
  pageRef = "about"
  weight = 10
[pt-br]
  languageCode = 'pt-br'
  languageName = 'Português'
  title = "Blog do Ricardinho"
  weight = 1
  [pt-br.menu]
  [[pt-br.menu.main]]
    identifier = "sobre"
    name = "Sobre"
    pageRef = "sobre"
    weight = 10