baseURL = "https://ricardosilva.xyz/"
title = "Blog do Ricardinho"
author = "Ricardo Silva"
copyright = "Ricardo Silva"
pagination.pagerSize = 10
languageCode = "pt-br"
defaultContentLanguage = "pt-br"
enableInlineShortcodes = true
theme = "tailwind"

# Multilingual configuration
defaultContentLanguageInSubdir = true
disableLanguages = []

ignoreErrors = ["error-remote-getjson"]
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true

[markup]
  _merge = "deep"

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  [params.header]
    logo = "file.svg"
    title = "Blog do Ricardinho"

  [params.footer]
    since = 2025
    poweredby = true

# Menu configuration is now in languages.toml for each language

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
