baseURL = "https://ricardosilva.xyz/"
title = "Blog do Ricardinho"
author = "Ricardo Silva"
copyright = "Ricardo Silva"
pagination.pagerSize = 10
languageCode = "pt-br"
defaultContentLanguage = "pt-br"
enableInlineShortcodes = true
theme = "tailwind"

ignoreErrors = ["error-remote-getjson"]
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true

[markup]
  _merge = "deep"

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  [params.header]
    logo = "file.svg"
    title = "Blog do Ricardinho"

  [params.footer]
    since = 2025
    poweredby = true

[menu]

  [[menu.main]]
    identifier = "post"
    name = "Post"
    pageRef = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"
series = "series"